---
- name: 'Stop and destroy the container.'
  delegate_to: "{{ pve_node }}"
  block:

  - name: 'Stop the container.'
    community.general.proxmox:
      api_user: "{{ pve_api_username }}"
      api_password: "{{ pve_api_password }}"
      api_host: "{{ pve_node }}"
      vmid: "{{ pve_vm_id }}"
      state: 'stopped'
      force: yes
      proxmox_default_behavior: 'no_defaults'
      timeout: 600
    ignore_errors: yes

  - name: 'Destroy the container.'
    community.general.proxmox:
      api_user: "{{ pve_api_username }}"
      api_password: "{{ pve_api_password }}"
      api_host: "{{ pve_node }}"
      vmid: "{{ pve_vm_id }}"
      state: 'absent'
      force: yes
      proxmox_default_behavior: 'no_defaults'
      timeout: 600
