---
- name: 'Run host-specific setup.'
  remote_user: 'root'
  block:

    - name: 'Gather facts.'
      ansible.builtin.setup:

    - name: 'Set OS and distribution facts.'
      ansible.builtin.include_tasks: 'set_os_facts.yaml'

    - name: 'Allow release-info to change for APT repositories.'
      ansible.builtin.command: 'apt-get update -y --allow-releaseinfo-change'
      changed_when: no

    - name: 'Install Apt packages.'
      ansible.builtin.apt:
        name: "{{ default_apt_packages }}"
        cache_valid_time: "{{ 3600 * 24 }}"

    - name: 'Make sure pip is at the latest version.'
      ansible.builtin.pip:
        name: 'pip'
        state: 'forcereinstall'
      changed_when: no

    - name: 'Install Pip packages.'
      ansible.builtin.pip:
        name: "{{ default_pip_packages }}"
        extra_args: '--ignore-installed'
