---
- name: 'Run host-specific setup.'
  remote_user: 'root'
  block:

    - name: 'Normal setup.'
      ansible.builtin.include_tasks: 'setup.yaml'

    - name: 'Install Docker.'
      ansible.builtin.include_role:
        name: 'lefford.docker'
        tasks_from: 'setup.yaml'

    - name: 'Install Dotfiles.'
      ansible.builtin.include_role:
        name: 'lefford.dotfiles'
        tasks_from: 'setup.yaml'
