---
- name: 'Remove the enterprise Proxmox package repository configuration.'
  ansible.builtin.apt_repository:
    repo: "{{ spn_repository_line }}"
    filename: 'pve-enterprise'
    state: 'absent'
  loop:
    - 'deb https://enterprise.proxmox.com/debian bullseye pve-enterprise'
    - 'deb https://enterprise.proxmox.com/debian/pve bullseye pve-enterprise'
  loop_control:
    loop_var: 'spn_repository_line'

- name: 'Add the community Proxmox package repository configuration.'
  ansible.builtin.apt_repository:
    repo: 'deb http://download.proxmox.com/debian/pve bullseye pve-no-subscription'
    filename: 'pve-community'

- name: 'Update system APT repositories.'
  ansible.builtin.apt_repository:
    repo: "{{ spn_repository_line }}"
  loop:
    - 'deb http://ftp.us.debian.org/debian bullseye main contrib'
    - 'deb http://ftp.us.debian.org/debian bullseye-updates main contrib'
    - 'deb http://ftp.us.debian.org/debian bullseye-backports main'
    - 'deb http://security.debian.org bullseye-security main contrib'
  loop_control:
    loop_var: 'spn_repository_line'
