---
- name: 'Enable IOMMU.'
  ansible.builtin.lineinfile:
    path: '/etc/default/grub'
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on iommu=pt"'
  register: 'default_grub'
  ignore_errors: yes

- name: 'Update Grub.'
  ansible.builtin.shell:
    cmd: 'update-grub2'
  when: 'default_grub.changed'
