---
- name: 'Modify some settings to prepare for Kubernetes.'
  ansible.builtin.copy:
    dest: '/etc/sysctl.d/kubernetes.conf'
    content: |
      vm.swappiness=0
      net.ipv4.ip_forward=1
      net.netfilter.nf_conntrack_max=131072
    mode: 0600

- name: 'Run all sysctl updates.'
  ansible.builtin.command:
    cmd: 'sysctl --system'
  changed_when: no

- name: 'Disable swap if not already disabled.'
  ansible.builtin.command:
    cmd: 'swapoff -a'
  changed_when: no
