---
- name: 'Ensure presence of relevant ZFS volumes for Proxmox hosts.'
  community.general.zfs:
    name: "{{ pve_local_share_prefix | regex_replace('^\\/', '') }}/{{ spn_local_hostname }}"
    state: 'present'
  loop: "{{ pve_local_share_hosts }}"
  loop_control:
    index_var: 'spn_index'
    loop_var: 'spn_local_hostname'
