---
- name: 'Set facts as empty lists.'
  ansible.builtin.set_fact:
    spn_hostnames: []
    spn_paths: []
    spn_ip_addresses: []
    spn_nfs_exports: []

- name: 'Build some basic facts.'
  ansible.builtin.set_fact:
    spn_hostnames: "{{ spn_hostnames + [ spn_k8s_host_name ] }}"
    spn_paths: "{{ spn_paths + [ k8s_nfs_prefix + '/' + hostvars[spn_k8s_host_name].k8s_cluster ] }}"
    spn_ip_addresses: "{{ spn_ip_addresses + [ hostvars[spn_k8s_host_name].pve_ip_address ] }}"
  loop: "{{ groups['k8s'] }}"
  loop_control:
    index_var: 'spn_index'
    loop_var: 'spn_k8s_host_name'

- name: 'Build list of NFS exports for Kubernetes clusters.'
  ansible.builtin.set_fact:
    spn_nfs_exports: "{{ spn_nfs_exports + [ spn_paths[spn_index] + ' ' + spn_ip_addresses[spn_index] + '/32(' + spn_nfs_mount_options + ')' ] }}"
  loop: "{{ spn_hostnames }}"
  loop_control:
    index_var: 'spn_index'
    loop_var: 'spn_k8s_host_name'

- name: 'Ensure presence of relevant ZFS volumes for Kubernetes clusters.'
  community.general.zfs:
    name: "{{ spn_paths[spn_index] | regex_replace('^\\/', '') }}"
    state: 'present'
  loop: "{{ k8s_master_hostnames }}"
  loop_control:
    index_var: 'spn_index'
    loop_var: 'spn_k8s_host_name'

- name: 'Export mountpoints for Kubernetes clusters.'
  ansible.builtin.blockinfile:
    path: '/etc/exports'
    block: "{{ spn_nfs_exports | join('\n') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (k8s_nfs_server)"
  register: 'spn_nfs_exports_block'

- name: 'Export exports.'
  ansible.builtin.command:
    cmd: 'exportfs -ra'
  when: 'spn_nfs_exports_block.changed'
